services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_development
      MYSQL_USER: rails
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: mysql2://rails:password@db:3306/todo_development
      RAILS_ENV: development
    volumes:
      - .:/rails
      - backend_bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "bundle install &&
             bundle exec rails db:create db:migrate &&
             bundle exec rails server -b 0.0.0.0"

  frontend:
    build:
      context: ../todo-frontend
      dockerfile: Dockerfile.dev
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    volumes:
      - ../todo-frontend:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - backend
    command: npm run dev

volumes:
  mysql_data:
  backend_bundle: